name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --prune --unshallow --tags

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      - name: Build with Gradle
        run: ./gradlew build

#      - name: Upload snapshot artifacts to Sonatype
#        id: upload_snapshot_artifacts
#        env:
#          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          GPG_KEY: ${{ secrets.GPG_KEY }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
