name: Maven release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        required: true
        description: "New version to be released, ex. '1.6.5'"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Release new version
        id: release
        run: |
          ./gradlew release \
            -Prelease.version=${{ github.event.inputs.releaseVersion }} \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}

#      - name: Upload release artifacts to Sonatype
#        id: upload_release_artifacts
#        env:
#          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          GPG_KEY: ${{ secrets.GPG_KEY }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          release_name: ${{ github.event.inputs.releaseVersion }}
          body: |
            ### ⭐ New Features
             - none
            ### 🐞 Bug fixes
             - none
          draft: true
          prerelease: false
